---
- name: Unarchive the binary
  vars:
    suffix_url: "{{ execution_default_binary_name }}-{{ berachain[type].execution.version }}-{{ ansible_system | lower }}-x64.zip"
  ansible.builtin.unarchive:
    src: "{{ berachain[type].execution.source_url }}/{{ suffix_url }}"
    dest: "{{ execution_bin_dir }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy binary file
  ansible.builtin.copy:
    src: "{{ execution_bin_dir }}/{{ execution_default_binary_name }}"
    dest: "{{ execution_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
