---
- name: Initialize execution data from genesis
  ansible.builtin.command:
    cmd: >-
      {{ execution_bin_dir }}/{{ service_identifier }} init
      --config {{ execution_config_file_path }}
      --datadir {{ execution_data_dir }}
      --chain {{ execution_genesis_file_path }}
  register: init_result
  changed_when: init_result.rc == 0
  failed_when: init_result.rc != 0

- name: Set ownership of data directory
  ansible.builtin.file:
    path: "{{ execution_data_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true
